export const ActionTypes = {
  GET_CARS_LIST_ERROR: 'GET_CARS_LIST_ERROR',
  GET_CARS_LIST_NOTIFY: 'GET_CARS_LIST_NOTIFY',
  GET_CARS_LIST_SUCCESS: 'GET_CARS_LIST_SUCCESS',

  GET_CAR_DETAILS_ERROR: 'GET_CAR_DETAILS_ERROR',
  GET_CAR_DETAILS_NOTIFY: 'GET_CAR_DETAILS_NOTIFY',
  GET_CAR_DETAILS_SUCCESS: 'GET_CAR_DETAILS_SUCCESS',

  GET_STATIC_DATA_ERROR: 'GET_STATIC_DATA_ERROR',
  GET_STATIC_DATA_NOTIFY: 'GET_STATIC_DATA_NOTIFY',
  GET_STATIC_DATA_SUCCESS: 'GET_STATIC_DATA_SUCCESS',
};
